"""
Django settings for ardurTrueAlign project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wt0_%27ipo5)5q$w^q0__tbe++rk7amy*6y%3-q5g061f1bpoa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['home.aurdurtechnology.com', 'www.home.aurdurtechnology.com']
ALLOWED_HOSTS = []



# Application definition
# Session Configuration
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Enhanced Session Management Configuration
ENHANCED_SESSION_CONFIG = {
    'IDLE_THRESHOLD_MINUTES': 5,
    'AUTO_LOGOUT_MINUTES': 30,
    'WARNING_THRESHOLD_MINUTES': 25,
    'HEARTBEAT_INTERVAL_SECONDS': 30,
    'MAX_ACTIVITY_BUFFER_SIZE': 100,
    'ENABLE_DEVICE_FINGERPRINTING': True,
    'ENABLE_SECURITY_MONITORING': True,
    'OFFICE_IPS': ['116.75.62.90'],  # Add your office IP addresses
    'MAX_REQUESTS_PER_MINUTE': 60,
    'CLEANUP_INTERVAL_HOURS': 24,
    'MAX_EVENTS_PER_SESSION': 1000,
}

# Caching Configuration (for rate limiting and session management)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trueAlign',
    'trueAlign.core',
    'trueAlign.profile',
    'trueAlign.shift',
    'trueAlign.support',
    'trueAlign.conf_booking',
    'trueAlign.attendance.apps.AttendanceConfig',  # ✅ keep this
    'trueAlign.sessions',
    'trueAlign.leave_management',
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'trueAlign.core.middleware.OptimizedSessionTrackingMiddleware',
    'trueAlign.core.middleware.OptimizedGlobalAuthenticationMiddleware',
]


ROOT_URLCONF = 'ardurTrueAlign.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'trueAlign/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'trueAlign.context_processors.is_admin',
                'trueAlign.context_processors.is_manager',
                'trueAlign.context_processors.is_employee',
                'trueAlign.context_processors.is_hr',
                'trueAlign.context_processors.is_backoffice',
                'trueAlign.context_processors.is_management',
                'trueAlign.context_processors.is_finance',
                'trueAlign.context_processors.appraisal_navigation',
            ],
        },
    },
]


WSGI_APPLICATION = 'ardurTrueAlign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ardurTrueAlign',
        'USER': 'root',
        'PASSWORD': '12345678',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Test database configuration
import sys

if 'test' in sys.argv or 'test_coverage' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test_db',         # Use a separate test database
        'USER': 'your_mysql_user',
        'PASSWORD': 'your_mysql_password',
        'HOST': 'localhost',
        'PORT': '3306',
        'TEST': {
            'NAME': 'test_db',     # Django will create & destroy this DB automatically
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Enhanced Logging Configuration for TrueAlign Support System
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{levelname}|{asctime}|{module}|{process}|{thread}|{message}',
            'style': '{',
        },
        'action_based': {
            'format': '[{asctime}] {levelname} - {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} - {name} - {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'action_based'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'shift_app.log'),
            'maxBytes': 1024*1024*15,
            'backupCount': 10,
            'formatter': 'detailed',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'shift_errors.log'),
            'maxBytes': 1024*1024*15,
            'backupCount': 10,
            'formatter': 'detailed',
        },
        'action_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'shift_actions.log'),
            'maxBytes': 1024*1024*15,
            'backupCount': 10,
            'formatter': 'json',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'shift_security.log'),
            'maxBytes': 1024*1024*15,
            'backupCount': 10,
            'formatter': 'detailed',
        },
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'shift_api.log'),
            'maxBytes': 1024*1024*15,
            'backupCount': 10,
            'formatter': 'json',
        },
        'cron_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'cron.log'),
            'maxBytes': 1024 * 1024 * 15,
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'support_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'support.log'),
            'maxBytes': 1024 * 1024 * 15,
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'support_error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'support_errors.log'),
            'maxBytes': 1024 * 1024 * 15,
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'support_api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'support_api.log'),
            'maxBytes': 1024 * 1024 * 15,
            'backupCount': 5,
            'formatter': 'json',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose'
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['error_file', 'support_error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console', 'support_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.shift': {
            'handlers': ['console', 'file', 'action_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.shift.actions': {
            'handlers': ['action_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.shift.security': {
            'handlers': ['security_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'trueAlign.shift.api': {
            'handlers': ['api_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.shift.performance': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.core.middleware': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'trueAlign.support': {
            'handlers': ['support_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.support.views': {
            'handlers': ['support_file', 'support_api_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.support.services': {
            'handlers': ['support_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.support.models': {
            'handlers': ['support_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.support.signals': {
            'handlers': ['support_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trueAlign.support.errors': {
            'handlers': ['support_error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}




# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL SETTINGS

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dhoteharshal16@gmail.com'  # Replace with your actual email
EMAIL_HOST_PASSWORD = 'qtwc pdwp hwkp geij'  # Replace with your app password, not regular password


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create directories for different types of uploads
TICKET_ATTACHMENTS_DIR = 'ticket_attachments'
COMMENT_ATTACHMENTS_DIR = 'comment_attachments'


import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# Additional authentication settings to prevent conflicts
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
