# Generated by Django 5.0.2 on 2025-05-02 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(help_text='General feedback and summary')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('period_start', models.DateField(help_text='Start date of the appraisal period')),
                ('period_end', models.DateField(help_text='End date of the appraisal period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('finance_comments', models.TextField(blank=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='appraisals', to='trueAlign.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_appraisals', 'Can view all appraisals'), ('manage_appraisals', 'Can manage appraisals'), ('finance_review', 'Can review appraisals from finance perspective')],
            },
        ),
        migrations.CreateModel(
            name='AppraisalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('challenge', 'Challenge'), ('goal', 'Goal for next period'), ('skill', 'Skill development'), ('feedback', 'Feedback for organization')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True, help_text='Impact or outcome of this item')),
                ('date', models.DateField(blank=True, help_text='Specific date related to this item', null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trueAlign.appraisal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_items', to='trueAlign.project')),
            ],
        ),
    ]
