# Generated by Django 4.2.21 on 2025-05-21 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trueAlign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text="Users to be CC'd on this ticket", related_name='cc_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
