# Generated by Django 5.0.2 on 2025-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.BooleanField(default=False, help_text='Allow carrying forward unused leaves'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_allowed',
            field=models.PositiveIntegerField(default=30, help_text='Maximum days allowed per year'),
        ),
    ]
