# Generated by Django 5.1.4 on 2025-02-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='support',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Related hardware/software asset ID', max_length=50),
        ),
        migrations.AddField(
            model_name='support',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='support',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='support',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='support',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, help_text='Parent ticket for related issues', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='trueAlign.support'),
        ),
        migrations.AddField(
            model_name='support',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='support',
            name='resolution_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='support',
            name='resolution_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='sla_breach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='support',
            name='assigned_to',
            field=models.CharField(choices=[('HR', 'HR'), ('IT Support L1', 'IT Support L1'), ('IT Support L2', 'IT Support L2'), ('Network Team', 'Network Team'), ('Security Team', 'Security Team'), ('Admin', 'Admin')], default='IT Support L1', max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='issue_type',
            field=models.CharField(choices=[('Hardware Issue', 'Hardware Issue'), ('Software Issue', 'Software Issue'), ('Network Issue', 'Network Issue'), ('Internet Issue', 'Internet Issue'), ('Application Issue', 'Application Issue'), ('HR Related Issue', 'HR Related Issue'), ('Access Management', 'Access Management'), ('Security Incident', 'Security Incident'), ('Service Request', 'Service Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending User Response', 'Pending User Response'), ('Pending Third Party', 'Pending Third Party'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['ticket_id'], name='trueAlign_s_ticket__676519_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['status'], name='trueAlign_s_status_69e152_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['created_at'], name='trueAlign_s_created_577e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['user'], name='trueAlign_s_user_id_6fec4b_idx'),
        ),
    ]
