# Generated by Django 5.1.4 on 2025-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_type',
            field=models.CharField(choices=[('Tea Break 1', 'Tea Break 1'), ('Lunch/Dinner Break', 'Lunch/Dinner Break'), ('Tea Break 2', 'Tea Break 2')], max_length=50),
        ),
    ]
