# Generated by Django 5.0.2 on 2025-11-24 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='current_office_location',
            field=models.ForeignKey(blank=True, help_text='Office where this session is taking place (resolved from GPS or IP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='trueAlign.officelocation'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='impossible_travel_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_location_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='travel_velocity_kmh',
            field=models.FloatField(blank=True, help_text='Speed between last two locations', null=True),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Unique fingerprint generated from device characteristics', max_length=255, unique=True)),
                ('device_name', models.CharField(help_text="Human-readable device name (e.g., 'Chrome on MacBook Pro')", max_length=200)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trust_level', models.IntegerField(default=0, help_text='0-100 trust score')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_addresses', models.JSONField(default=list, help_text='Historical list of IP addresses used by this device')),
                ('locations_used', models.JSONField(default=list, help_text='List of locations this device has been used from')),
                ('session_count', models.IntegerField(default=0)),
                ('last_session_id', models.UUIDField(blank=True, null=True)),
                ('suspicious_activity_count', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trueAlign_userdevice',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['user', 'device_fingerprint'], name='user_device_fp_idx'), models.Index(fields=['is_trusted'], name='device_trusted_idx'), models.Index(fields=['last_seen'], name='device_last_seen_idx')],
            },
        ),
    ]
