# Generated by Django 5.0.2 on 2025-06-07 08:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload attachment file', upload_to='comment_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size of the file in bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the attachment was uploaded')),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attachment is active')),
            ],
            options={
                'verbose_name': 'Comment Attachment',
                'verbose_name_plural': 'Comment Attachments',
                'db_table': 'truealign_comment_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='support',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text="Users to be CC'd on this ticket", related_name='cc_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='support',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this ticket has been reopened'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='auto_logout_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='background_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='usersession',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='broadcast_messages_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='broadcast_messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser_fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='click_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='connection_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='cross_tab_activity_syncs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='csrf_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='custom_timeout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='engagement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='error_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='inactivity_warnings_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_primary_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='keyboard_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_warning_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='mouse_movements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='network_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='offline_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='page_views',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='parent_session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='pending_sync_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='productivity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='scroll_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='security_incidents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_quality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_last_focus',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_switches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_total_focus_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_visibility_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='timezone_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['tab_id'], name='trueAlign_u_tab_id_4ec956_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['parent_session_id'], name='trueAlign_u_parent__19d321_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='trueAlign_u_last_ac_267f65_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active', 'parent_session_id'], name='trueAlign_u_user_id_37552b_idx'),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='ticket_activity',
            field=models.ForeignKey(help_text='The ticket activity/comment this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', to='trueAlign.ticketactivity'),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
