# Generated by Django 5.2.8 on 2025-11-27 17:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=255)),
                ('type', models.CharField(choices=[('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('PROMOTION', 'Promotion Letter'), ('INCREMENT', 'Increment Letter'), ('RELIEVING', 'Relieving Letter'), ('EXPERIENCE', 'Experience Letter'), ('TRANSFER', 'Transfer Letter'), ('WARNING', 'Warning Letter'), ('SHOW_CAUSE', 'Show Cause Notice'), ('TERMINATION', 'Termination Letter'), ('NON_COMPLIANCE', 'Non-Compliance Notice'), ('ATTENDANCE_VIOLATION', 'Attendance Violation Letter'), ('INTERNSHIP', 'Internship Confirmation'), ('TRAINING', 'Training Completion Letter'), ('REMOTE_WORK', 'Remote Work Approval'), ('POLICY_VIOLATION', 'Policy Violation Advisory'), ('LEAVE_ACTION', 'Leave Approval / Rejection'), ('CERT_APPRECIATION', 'Certificate of Appreciation'), ('CERT_ACHIEVEMENT', 'Certificate of Achievement'), ('CERT_EXCELLENCE', 'Certificate of Excellence'), ('CERT_PARTICIPATION', 'Certificate of Participation'), ('CERT_PROJECT', 'Certificate for Project Completion'), ('OTHER', 'Other')], help_text='Type of Letter', max_length=50)),
                ('content', models.TextField(help_text='HTML Content with placeholders (e.g., {{employee_name}})')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLetterTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=255)),
                ('type', models.CharField(choices=[('OFFER', 'Offer Letter'), ('APPOINTMENT', 'Appointment Letter'), ('PROMOTION', 'Promotion Letter'), ('INCREMENT', 'Increment Letter'), ('RELIEVING', 'Relieving Letter'), ('EXPERIENCE', 'Experience Letter'), ('TRANSFER', 'Transfer Letter'), ('WARNING', 'Warning Letter'), ('SHOW_CAUSE', 'Show Cause Notice'), ('TERMINATION', 'Termination Letter'), ('NON_COMPLIANCE', 'Non-Compliance Notice'), ('ATTENDANCE_VIOLATION', 'Attendance Violation Letter'), ('INTERNSHIP', 'Internship Confirmation'), ('TRAINING', 'Training Completion Letter'), ('REMOTE_WORK', 'Remote Work Approval'), ('POLICY_VIOLATION', 'Policy Violation Advisory'), ('LEAVE_ACTION', 'Leave Approval / Rejection'), ('CERT_APPRECIATION', 'Certificate of Appreciation'), ('CERT_ACHIEVEMENT', 'Certificate of Achievement'), ('CERT_EXCELLENCE', 'Certificate of Excellence'), ('CERT_PARTICIPATION', 'Certificate of Participation'), ('CERT_PROJECT', 'Certificate for Project Completion'), ('OTHER', 'Other')], help_text='Type of Letter', max_length=50)),
                ('content', models.TextField(help_text='HTML Content with placeholders (e.g., {{employee_name}})')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical letter template',
                'verbose_name_plural': 'historical letter templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGeneratedLetter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField(help_text='Final HTML content of the letter')),
                ('pdf_file', models.TextField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, help_text='Employee for whom the letter is generated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='HR User who generated the letter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trueAlign.lettertemplate')),
            ],
            options={
                'verbose_name': 'historical generated letter',
                'verbose_name_plural': 'historical generated letters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Final HTML content of the letter')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_letters/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee for whom the letter is generated', on_delete=django.db.models.deletion.CASCADE, related_name='letters_received', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(help_text='HR User who generated the letter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_generated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_letters', to='trueAlign.lettertemplate')),
            ],
        ),
    ]
