# Generated by Django 5.0.2 on 2025-04-29 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_overtime_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trueAlign.usersession",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="expected_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="location",
            field=models.CharField(
                choices=[
                    ("Office", "Office"),
                    ("Home", "Home"),
                    ("Remote", "Remote"),
                    ("Other", "Other"),
                ],
                default="Office",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="regularization_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                    ("Half Day", "Half Day"),
                    ("On Leave", "On Leave"),
                    ("Work From Home", "Work From Home"),
                    ("Weekend", "Weekend"),
                    ("Holiday", "Holiday"),
                    ("Comp Off", "Comp Off"),
                ],
                default="Absent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="trueAlign_a_date_c92f26_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["user", "status"], name="trueAlign_a_user_id_c1b091_idx"
            ),
        ),
    ]
