# Generated by Django 5.0.2 on 2025-08-04 16:41

import django.db.models.deletion
import trueAlign.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'User Created'), ('update', 'User Updated'), ('status_change', 'Status Changed'), ('role_change', 'Role Changed'), ('deactivate', 'User Deactivated'), ('activate', 'User Activated'), ('password_reset', 'Password Reset')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, validators=[trueAlign.models.validate_future_date], verbose_name='Date of Birth')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Select blood group', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('other', 'Other')], max_length=20, null=True)),
                ('contact_number_primary', models.CharField(blank=True, help_text='Primary contact number with country code', max_length=15, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_email', models.EmailField(blank=True, help_text='Official company email', max_length=254, null=True, unique=True)),
                ('current_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('current_country', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current_same_as_permanent', models.BooleanField(default=False, help_text='Is current address same as permanent address?')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_type', models.CharField(blank=True, choices=[('full_time', 'Full-Time Employee'), ('part_time', 'Part-Time Employee'), ('contract', 'Contract Employee'), ('intern', 'Intern'), ('consultant', 'Consultant'), ('probationary', 'Probationary Employee'), ('remote', 'Remote Worker')], max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('senior_developer', 'Senior Developer'), ('developer', 'Developer'), ('junior_developer', 'Junior Developer'), ('intern', 'Intern'), ('qa_engineer', 'QA Engineer'), ('devops_engineer', 'DevOps Engineer'), ('ui_ux_designer', 'UI/UX Designer'), ('business_analyst', 'Business Analyst'), ('project_manager', 'Project Manager'), ('scrum_master', 'Scrum Master'), ('consultant', 'Consultant'), ('trainee', 'Trainee'), ('other', 'Other')], default='developer', help_text='Employee role/designation in the company', max_length=50)),
                ('hire_date', models.DateField(blank=True, help_text='Date when offer was accepted', null=True)),
                ('start_date', models.DateField(blank=True, help_text='First day of work', null=True)),
                ('probation_end_date', models.DateField(blank=True, help_text='Date when probation period ends', null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text='Notice period in days')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('suspended', 'Suspended'), ('absconding', 'Absconding'), ('probation', 'Probation'), ('notice_period', 'Notice Period'), ('sabbatical', 'Sabbatical'), ('long_leave', 'Long Leave')], db_index=True, default='probation', max_length=50)),
                ('exit_date', models.DateField(blank=True, help_text='Last working day', null=True)),
                ('exit_reason', models.TextField(blank=True, help_text='Reason for leaving the company', null=True)),
                ('rehire_eligibility', models.BooleanField(blank=True, help_text='Eligible for rehire', null=True)),
                ('salary_currency', models.CharField(default='INR', help_text='Currency code (e.g., INR, USD)', max_length=3)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, validators=[trueAlign.models.validate_pan], verbose_name='PAN Number')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, validators=[trueAlign.models.validate_aadhar], verbose_name='Aadhar Number')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_position', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('onboarding_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('confidential_notes', models.TextField(blank=True, help_text='Confidential HR notes (visible only to HR)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_location', models.ForeignKey(blank=True, help_text='Office location where the employee works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='trueAlign.officelocation')),
                ('onboarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_users', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'permissions': [('view_confidential_notes', 'Can view confidential HR notes'), ('view_salary_information', 'Can view salary information'), ('export_employee_data', 'Can export employee data'), ('manage_employee_status', 'Can change employee status')],
                'indexes': [models.Index(fields=['employment_status'], name='trueAlign_u_employm_5039f7_idx'), models.Index(fields=['employee_type'], name='trueAlign_u_employe_bda06a_idx'), models.Index(fields=['office_location'], name='trueAlign_u_office__bfd620_idx'), models.Index(fields=['hire_date'], name='trueAlign_u_hire_da_98da4c_idx'), models.Index(fields=['start_date'], name='trueAlign_u_start_d_f34b79_idx')],
            },
        ),
    ]
