# Generated by Django 5.0.2 on 2025-06-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
