# Generated by Django 5.0.2 on 2025-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_usersession_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(default='4ba157d1b48e42a894263f6749c320c9', max_length=40),
            preserve_default=False,
        ),
    ]
