# Generated by Django 5.0.2 on 2025-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_commentattachment_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/%Y/%m/%d/'),
        ),
    ]
