# Generated by Django 5.0.2 on 2025-11-07 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_being_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag to prevent concurrent processing'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, help_text='Last time this record was processed', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='processing_lock_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for processing lock', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In'), ('Half Day', 'Half Day')], db_index=True, default='Not Marked', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_being_processed', 'date'], name='trueAlign_a_is_bein_e35f66_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['version', 'user', 'date'], name='trueAlign_a_version_80b4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['last_modified'], name='trueAlign_a_last_mo_c983ec_idx'),
        ),
    ]
