# Generated by Django 5.1.4 on 2025-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_alter_attendance_clock_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
