# Generated by Django 5.2.8 on 2025-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0002_lettertemplate_historicallettertemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallettertemplate",
            name="placeholders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of placeholders used in the template",
            ),
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="placeholders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of placeholders used in the template",
            ),
        ),
    ]
