# Generated by Django 5.0.2 on 2025-05-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_appraisal_appraisalitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-period_end', '-last_modified'], 'permissions': [('review_appraisal', 'Can review appraisals'), ('approve_appraisal', 'Can approve appraisals'), ('view_all_appraisals', 'Can view all appraisals')]},
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='reviewed_at',
            new_name='finance_review_date',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='finance_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='manager_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finance_rejected', 'Finance Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AppraisalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finance_rejected', 'Finance Rejected')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finance_rejected', 'Finance Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='trueAlign.appraisal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
