# Generated by Django 5.0.2 on 2025-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0002_attendance_is_overtime_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="session_duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
