# Generated by Django 5.1.4 on 2025-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0002_alter_support_options_support_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='assigned_to',
            field=models.CharField(choices=[('HR', 'HR'), ('Admin', 'Admin')], default='IT Support L1', max_length=50),
        ),
    ]
