# Generated by Django 5.0.2 on 2025-05-03 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_alter_appraisal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisalitem',
            options={'ordering': ['category', '-date']},
        ),
        migrations.AddField(
            model_name='appraisalitem',
            name='reviewer_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appraisalitem',
            name='reviewer_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalitem',
            name='category',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('goal', 'Goal'), ('competency', 'Competency'), ('development', 'Development'), ('feedback', 'Feedback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisalitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalitem',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appraisalitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appraisalworkflow',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisalworkflow',
            name='from_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalworkflow',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appraisalworkflow',
            name='to_status',
            field=models.CharField(max_length=20),
        ),
    ]
