# Generated by Django 5.0.2 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0003_usersession_session_duration_usersession_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftmaster",
            name="custom_work_days",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated day names (Monday,Tuesday,etc.)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shiftmaster",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
