# Generated by Django 5.2.8 on 2025-12-02 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0003_historicallettertemplate_placeholders_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the cash box (e.g., 'Main Safe', 'Petty Cash')",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="Physical location", max_length=255),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current cash balance",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        help_text="Person responsible for this cash box",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_cash_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit (In)"),
                            ("WITHDRAWAL", "Withdrawal (Out)"),
                            ("EXPENSE", "Direct Expense Payment"),
                            ("TRANSFER", "Transfer to another Box/Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(help_text="Reason for transaction")),
                (
                    "attachments",
                    models.FileField(blank=True, null=True, upload_to="cash_receipts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="trueAlign.cashbox",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_cash_txns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_bank_payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this cash came from a bank withdrawal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_cash_txns",
                        to="trueAlign.bankpayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_source_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Payment"),
                            ("CASH", "Cash Transaction"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of this payment assigned to this expense",
                        max_digits=15,
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="trueAlign.bankpayment",
                    ),
                ),
                (
                    "cash_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="trueAlign.cashtransaction",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="trueAlign.dailyexpense",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="trueAlign.voucher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShadowEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Shadow Income"),
                            ("EXPENSE", "Shadow Expense"),
                            ("ADJUSTMENT", "Book Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        help_text="Internal category for analysis", max_length=100
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=True, help_text="High security clearance required"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_cash_box",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this affected a cash box balance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trueAlign.cashbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of the salary month")),
                (
                    "formal_salary_payable",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net salary as per Payslip",
                        max_digits=15,
                    ),
                ),
                (
                    "actual_payout_bank",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually transferred via Bank",
                        max_digits=15,
                    ),
                ),
                (
                    "actual_payout_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount paid in Cash",
                        max_digits=15,
                    ),
                ),
                (
                    "cash_returned_by_employee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash returned by employee to company (Kickback/Adjustment)",
                        max_digits=15,
                    ),
                ),
                (
                    "loan_recovery_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Deducted for loan recovery (often not on payslip)",
                        max_digits=15,
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True, help_text="Explanation for the difference"
                    ),
                ),
                (
                    "is_shadow_record",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this is for internal 'Real' tracking only",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_payroll_adjs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "month")},
            },
        ),
    ]
