# Generated by Django 5.0.2 on 2025-08-09 10:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_layoutpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('recurring_yearly', models.BooleanField(default=True, help_text='If True, this holiday occurs on the same date every year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='ShiftMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_duration', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('break_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('grace_period', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('work_days', models.CharField(choices=[('Weekdays', 'Monday to Friday'), ('All Days', 'Monday to Saturday'), ('Custom', 'Custom Days')], default='Weekdays', max_length=20)),
                ('custom_work_days', models.CharField(blank=True, help_text='Comma-separated day names (Monday,Tuesday,etc.)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trueAlign.shiftmaster')),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
                'indexes': [models.Index(fields=['user', 'effective_from'], name='trueAlign_s_user_id_f0dd6b_idx'), models.Index(fields=['is_current'], name='trueAlign_s_is_curr_9ea5e0_idx')],
            },
        ),
    ]
