# Generated by Django 5.0.2 on 2025-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_ticketattachment_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
