# Generated by Django 5.1.4 on 2025-02-09 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_alter_support_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterField(
            model_name='support',
            name='assigned_to',
            field=models.CharField(choices=[('HR', 'HR'), ('Admin', 'Admin')], default='HR', max_length=50),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['due_date'], name='trueAlign_s_due_dat_c6bcc3_idx'),
        ),
    ]
