# Generated by Django 5.0.2 on 2025-06-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_usersession_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name', max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('CONFERENCE', 'Conference Room'), ('HUDDLE', 'Huddle Room'), ('MEETING', 'Meeting Room'), ('BOARD', 'Board Room')], default='CONFERENCE', max_length=15)),
                ('capacity', models.PositiveIntegerField(default=8, help_text='Maximum seating capacity')),
                ('location', models.CharField(blank=True, help_text='Room location/floor', max_length=100)),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (e.g., Projector, Whiteboard, Video Conferencing)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per hour (if applicable)', max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Room description')),
                ('image', models.ImageField(blank=True, help_text='Room photo', null=True, upload_to='room_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Total bookings made')),
                ('total_hours_booked', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours booked', max_digits=10)),
            ],
            options={
                'verbose_name': 'Conference Room',
                'verbose_name_plural': 'Conference Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='Purpose of the meeting', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional meeting details')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendees_count', models.PositiveIntegerField(default=1, help_text='Expected number of attendees')),
                ('external_attendees', models.PositiveIntegerField(default=0, help_text='Number of external/guest attendees')),
                ('meeting_type', models.CharField(choices=[('INTERNAL', 'Internal Meeting'), ('CLIENT', 'Client Meeting'), ('INTERVIEW', 'Interview'), ('TRAINING', 'Training'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], default='INTERNAL', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('recurring_pattern', models.CharField(choices=[('NONE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('no_show', models.BooleanField(default=False, help_text="Meeting didn't happen")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per hour for this booking', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of booking', max_digits=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_bookings', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('parent_booking', models.ForeignKey(blank=True, help_text='Original booking for recurring series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to='trueAlign.conferencebooking')),
                ('room', models.ForeignKey(help_text='Conference room being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trueAlign.room')),
            ],
            options={
                'verbose_name': 'Conference Room Booking',
                'verbose_name_plural': 'Conference Room Bookings',
                'ordering': ['-created_at', 'start_time'],
                'indexes': [models.Index(fields=['room', 'start_time', 'status'], name='trueAlign_c_room_id_0ca4c5_idx'), models.Index(fields=['booked_by', 'status'], name='trueAlign_c_booked__c5f6f2_idx'), models.Index(fields=['start_time', 'end_time'], name='trueAlign_c_start_t_9c696e_idx'), models.Index(fields=['status', 'created_at'], name='trueAlign_c_status_1d7a30_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conferencebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('room', 'start_time', 'end_time'), name='unique_confirmed_booking_slot'),
        ),
        migrations.AddConstraint(
            model_name='conferencebooking',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='conferencebooking',
            constraint=models.CheckConstraint(check=models.Q(('attendees_count__gte', 1)), name='minimum_one_attendee'),
        ),
    ]
