# Generated by Django 5.1.4 on 2025-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_chatgroup_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
