# Generated by Django 5.0.2 on 2025-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0003_attendance_is_being_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='parent_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
