# Generated by Django 5.2.8 on 2025-12-02 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0004_cashbox_cashtransaction_paymentallocation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bank_statements/")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="True if lines have been extracted"
                    ),
                ),
                ("total_lines", models.IntegerField(default=0)),
                ("reconciled_lines", models.IntegerField(default=0)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="trueAlign.bankaccount",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "description",
                    models.TextField(help_text="Raw description from bank"),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, help_text="UTR / Ref No", max_length=100, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_reconciled", models.BooleanField(default=False)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match_confidence",
                    models.FloatField(default=0.0, help_text="0.0 to 1.0 score"),
                ),
                ("match_notes", models.TextField(blank=True)),
                (
                    "matched_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_lines",
                        to="trueAlign.bankpayment",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="trueAlign.bankstatement",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "amount"], name="trueAlign_b_date_be7657_idx"
                    ),
                    models.Index(
                        fields=["reference_no"], name="trueAlign_b_referen_8631cb_idx"
                    ),
                ],
            },
        ),
    ]
