# Generated by Django 5.0.2 on 2025-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0004_alter_shiftmaster_custom_work_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time_zone",
            field=models.CharField(default="Asia/Kolkata", max_length=50),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Present & Late", "Present & Late"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                    ("Half Day", "Half Day"),
                    ("On Leave", "On Leave"),
                    ("Work From Home", "Work From Home"),
                    ("Weekend", "Weekend"),
                    ("Holiday", "Holiday"),
                    ("Comp Off", "Comp Off"),
                ],
                default="Absent",
                max_length=20,
            ),
        ),
    ]
