# Generated by Django 5.0.2 on 2025-05-03 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_alter_appraisalitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-period_end', 'user__last_name'], 'permissions': [('can_view_all_appraisals', 'Can view all appraisals'), ('can_manage_appraisals', 'Can manage all appraisals')]},
        ),
        migrations.AlterModelOptions(
            name='appraisalitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appraisalworkflow',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='finance_review_date',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='manager_review_date',
            new_name='submitted_at',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='appraisalitem',
            old_name='impact',
            new_name='manager_comments',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='finance_comments',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='finance_reviewer',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='manager_comments',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='appraisalitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='appraisalitem',
            name='reviewer_comments',
        ),
        migrations.RemoveField(
            model_name='appraisalitem',
            name='reviewer_rating',
        ),
        migrations.AddField(
            model_name='appraisalitem',
            name='employee_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='appraisalitem',
            name='manager_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('hr_review', 'HR Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisalitem',
            name='category',
            field=models.CharField(choices=[('goal', 'Goal'), ('achievement', 'Achievement'), ('improvement', 'Area for Improvement'), ('training', 'Training Completed'), ('feedback', 'Feedback Received')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisalworkflow',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AppraisalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appraisal_attachments/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trueAlign.appraisal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
