# Generated by Django 5.0.2 on 2025-11-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_alter_usersession_parent_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='regularization_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the regularization was processed', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the regularization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_remarks',
            field=models.TextField(blank=True, help_text='Admin remarks on regularization decision', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the regularization was requested', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested the regularization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_requested_status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In'), ('Half Day', 'Half Day')], help_text='Status requested during regularization', max_length=20, null=True),
        ),
    ]
