# Generated by Django 5.0.2 on 2025-11-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_alter_usersession_parent_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Room name (e.g., 'Board Room', 'Meeting Room A')", max_length=100)),
                ('floor', models.CharField(help_text="Floor number or name (e.g., '2nd Floor', 'Ground')", max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people the room can accommodate')),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenities (e.g., ['Projector', 'Whiteboard', 'Video Conference'])")),
                ('buffer_time_minutes', models.PositiveIntegerField(default=15, help_text='Buffer time between bookings (in minutes) for cleaning/setup')),
                ('min_lead_time_minutes', models.PositiveIntegerField(default=15, help_text='Minimum lead time required before booking start (in minutes)')),
                ('max_booking_duration_hours', models.PositiveIntegerField(default=3, help_text='Maximum duration for a single booking (in hours)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this room available for booking? Inactive rooms cannot be booked.')),
                ('description', models.TextField(blank=True, help_text='Additional room description or special instructions')),
                ('image', models.ImageField(blank=True, help_text='Room image', null=True, upload_to='conference_rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('office_location', models.ForeignKey(help_text='Office location where this room is located', on_delete=django.db.models.deletion.CASCADE, related_name='conference_rooms', to='trueAlign.officelocation')),
            ],
            options={
                'verbose_name': 'Conference Room',
                'verbose_name_plural': 'Conference Rooms',
                'ordering': ['office_location', 'floor', 'name'],
                'unique_together': {('office_location', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title or purpose', max_length=200)),
                ('purpose', models.TextField(help_text='Detailed purpose of the meeting')),
                ('attendees', models.TextField(help_text='List of attendees (names or emails, one per line or comma-separated)')),
                ('attendee_count', models.PositiveIntegerField(help_text='Number of attendees')),
                ('start_time', models.DateTimeField(help_text='Booking start date and time')),
                ('end_time', models.DateTimeField(help_text='Booking end date and time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current booking status', max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or setup needed')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Conference room being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trueAlign.conferenceroom')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['room', 'start_time', 'end_time'], name='trueAlign_r_room_id_4b5f4c_idx'), models.Index(fields=['booked_by', 'status'], name='trueAlign_r_booked__0c05a7_idx'), models.Index(fields=['status', 'start_time'], name='trueAlign_r_status_e0e40d_idx')],
            },
        ),
    ]
