# Generated by Django 5.1.4 on 2025-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_groupmember_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='typing_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
