# Generated by Django 5.0.2 on 2025-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0004_globalupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalupdate",
            name="description_hi",
            field=models.TextField(
                blank=True, help_text="Hindi translation of description", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalupdate",
            name="description_mr",
            field=models.TextField(
                blank=True, help_text="Marathi translation of description", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalupdate",
            name="primary_language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("mr", "Marathi")],
                default="en",
                help_text="Primary language of the update",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="globalupdate",
            name="title_hi",
            field=models.CharField(
                blank=True,
                help_text="Hindi translation of title",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalupdate",
            name="title_mr",
            field=models.CharField(
                blank=True,
                help_text="Marathi translation of title",
                max_length=255,
                null=True,
            ),
        ),
    ]
