# Generated by Django 5.0.2 on 2025-07-01 04:49

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_room_conferencebooking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'user__username']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 1, 4, 49, 44, 126720, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='breaks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='early_departure_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(choices=[('Office', 'Office'), ('Home', 'Home'), ('Remote', 'Remote'), ('Client Site', 'Client Site'), ('Other', 'Other')], default='Office', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='regularization_attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='requested_status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In'), ('Half Day', 'Half Day')], help_text='Status requested by employee during regularization', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In'), ('Half Day', 'Half Day')], default='Not Marked', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['regularization_status'], name='trueAlign_a_regular_148211_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['clock_in_time'], name='trueAlign_a_clock_i_aa9175_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['clock_out_time'], name='trueAlign_a_clock_o_88645b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_weekend', 'is_holiday'], name='trueAlign_a_is_week_ebd761_idx'),
        ),
    ]
