# Generated by Django 5.0.2 on 2025-06-08 05:50

import trueAlign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_alter_support_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=trueAlign.models.CommentAttachment.comment_attachment_path),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=trueAlign.models.TicketAttachment.ticket_attachment_path),
        ),
    ]
