# Generated by Django 5.0.2 on 2025-08-09 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0004_holiday_shiftmaster_shiftassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about this assignment"
            ),
        ),
        migrations.AlterField(
            model_name="shiftassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="trueAlign.shiftmaster",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="trueAlign_s_effecti_9e7884_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["shift", "effective_from"],
                name="trueAlign_s_shift_i_78b53c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftmaster",
            index=models.Index(
                fields=["name", "is_active"], name="trueAlign_s_name_025c60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftmaster",
            index=models.Index(
                fields=["start_time", "end_time"], name="trueAlign_s_start_t_ba4f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftmaster",
            index=models.Index(
                fields=["is_active"], name="trueAlign_s_is_acti_3737e1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user", "effective_from"),
                name="unique_current_assignment_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="valid_date_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftmaster",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("shift_duration__gte", 0.5), ("shift_duration__lte", 24.0)
                ),
                name="shift_duration_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftmaster",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_shift_name"
            ),
        ),
    ]
