# Generated by Django 5.0.2 on 2025-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0004_escalationrule_ticketfieldchange_tickettag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
