# Generated by Django 5.1.4 on 2025-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0005_groupmember_typing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Loss of Pay', 'Loss of Pay'), ('Half Day', 'Half Day'), ('Emergency', 'Emergency')], max_length=50),
        ),
    ]
