# Generated by Django 5.0.2 on 2025-04-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0005_attendance_time_zone_alter_attendance_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="time_zone",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Present & Late", "Present & Late"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                    ("Half Day", "Half Day"),
                    ("On Leave", "On Leave"),
                    ("Work From Home", "Work From Home"),
                    ("Weekend", "Weekend"),
                    ("Holiday", "Holiday"),
                    ("Comp Off", "Comp Off"),
                    ("Not Marked", "Not Marked"),
                ],
                default="Not Marked",
                max_length=20,
            ),
        ),
    ]
