# Generated by Django 5.0.2 on 2025-09-16 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0005_add_globalupdate_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_type', models.CharField(choices=[('Hardware Issue', 'Hardware Issue'), ('Software Issue', 'Software Issue'), ('Network Issue', 'Network Issue'), ('Internet Issue', 'Internet Issue'), ('Application Issue', 'Application Issue'), ('HR Related Issue', 'HR Related Issue'), ('Access Management', 'Access Management'), ('Security Incident', 'Security Incident'), ('Service Request', 'Service Request')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending User Response', 'Pending User Response'), ('Pending Third Party', 'Pending Third Party'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('assigned_group', models.CharField(blank=True, choices=[('HR', 'HR'), ('Admin', 'Admin')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('asset_id', models.CharField(blank=True, help_text='Related hardware/software asset ID', max_length=50)),
                ('sla_breach', models.BooleanField(default=False)),
                ('sla_target_date', models.DateTimeField(blank=True, help_text='Target date for SLA compliance', null=True)),
                ('sla_status', models.CharField(blank=True, choices=[('Within SLA', 'Within SLA'), ('Breached', 'Breached')], help_text='Status of SLA compliance', max_length=20, null=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('response_time', models.DurationField(blank=True, help_text='Time taken for first response', null=True)),
                ('time_to_close', models.DurationField(blank=True, help_text='Total time from creation to closure', null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, help_text='Current escalation level of the ticket')),
                ('reopen_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times this ticket has been reopened')),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('cc_users', models.ManyToManyField(blank=True, help_text="Users to be CC'd on this ticket", related_name='cc_tickets', to=settings.AUTH_USER_MODEL)),
                ('parent_ticket', models.ForeignKey(blank=True, help_text='Parent ticket for related issues', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='trueAlign.support')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending User Response', 'Pending User Response'), ('Pending Third Party', 'Pending Third Party'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='trueAlign.support')),
            ],
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('COMMENTED', 'Commented'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activity', to='trueAlign.support')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('formatted_filename', models.CharField(blank=True, help_text='Formatted filename with ticket ID and number', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trueAlign.support')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes only visible to staff')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trueAlign.support')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload attachment file', upload_to='comment_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('formatted_filename', models.CharField(blank=True, help_text='Formatted filename with ticket ID and number', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size of the file in bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the attachment was uploaded')),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attachment is active')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_activity', models.ForeignKey(help_text='The ticket activity/comment this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', to='trueAlign.ticketactivity')),
                ('comment', models.ForeignKey(help_text='The comment this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trueAlign.ticketcomment')),
            ],
            options={
                'verbose_name': 'Comment Attachment',
                'verbose_name_plural': 'Comment Attachments',
                'db_table': 'truealign_comment_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['ticket_id'], name='trueAlign_s_ticket__676519_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['status'], name='trueAlign_s_status_69e152_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['created_at'], name='trueAlign_s_created_577e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['user'], name='trueAlign_s_user_id_6fec4b_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['due_date'], name='trueAlign_s_due_dat_c6bcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['resolved_at'], name='trueAlign_s_resolve_70ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['priority'], name='trueAlign_s_priorit_933347_idx'),
        ),
    ]
