# Generated by Django 5.0.2 on 2025-05-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0005_alter_appraisal_options_alter_appraisalitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='appraisal',
            options={},
        ),
        migrations.DeleteModel(
            name='ChartOfAccount',
        ),
        migrations.DeleteModel(
            name='ClientPayment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
