# Generated by Django 5.0.2 on 2025-11-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0005_attendance_regularization_processed_at_and_more'),
        ('trueAlign', '0005_conferenceroom_roombooking'),
    ]

    operations = [
    ]
