# Generated by Django 5.0.2 on 2025-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0005_alter_commentattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='formatted_filename',
            field=models.CharField(blank=True, help_text='Formatted filename with ticket ID and number', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='formatted_filename',
            field=models.CharField(blank=True, help_text='Formatted filename with ticket ID and number', max_length=255),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(help_text='Upload attachment file', upload_to='comment_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='ticket_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='original_filename',
            field=models.CharField(help_text='Original name of the uploaded file', max_length=255),
        ),
    ]
