# Generated by Django 5.0.2 on 2025-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trueAlign",
            "0006_support_statuslog_ticketactivity_ticketattachment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="support",
            name="department",
        ),
        migrations.AlterField(
            model_name="support",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
