# Generated by Django 5.0.2 on 2025-11-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0006_merge_20251109_2005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_processed_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_processed_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_remarks',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_requested_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_requested_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_requested_status',
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Appraisal title', max_length=200)),
                ('overview', models.TextField(help_text='Overall performance overview')),
                ('period_start', models.DateField(help_text='Appraisal period start date')),
                ('period_end', models.DateField(help_text='Appraisal period end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hr_review', 'HR Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current appraisal status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When employee submitted', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When finally approved', null=True)),
                ('manager', models.ForeignKey(help_text='Manager responsible for this appraisal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee being appraised', on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attachment file', upload_to='appraisals/attachments/%Y/%m/')),
                ('title', models.CharField(help_text='Attachment title/description', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(help_text='Parent appraisal', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trueAlign.appraisal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_appraisal_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Attachment',
                'verbose_name_plural': 'Appraisal Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('project', 'Project Completion'), ('skill', 'Skill Development'), ('initiative', 'Initiative'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership'), ('other', 'Other')], help_text='Category of this achievement/item', max_length=20)),
                ('title', models.CharField(help_text='Item title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description')),
                ('date', models.DateField(blank=True, help_text='Date of achievement/completion', null=True)),
                ('employee_rating', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], help_text='Employee self-rating', null=True)),
                ('manager_rating', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], help_text='Manager rating', null=True)),
                ('manager_comments', models.TextField(blank=True, help_text="Manager's comments on this item")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.ForeignKey(help_text='Parent appraisal', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trueAlign.appraisal')),
            ],
            options={
                'verbose_name': 'Appraisal Item',
                'verbose_name_plural': 'Appraisal Items',
                'ordering': ['category', '-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Previous status', max_length=20, null=True)),
                ('to_status', models.CharField(help_text='New status', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Comments/notes for this action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appraisal', models.ForeignKey(help_text='Parent appraisal', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='trueAlign.appraisal')),
            ],
            options={
                'verbose_name': 'Appraisal Workflow',
                'verbose_name_plural': 'Appraisal Workflows',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['user', 'status'], name='trueAlign_a_user_id_0171e5_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['manager', 'status'], name='trueAlign_a_manager_9712ef_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['status', '-created_at'], name='trueAlign_a_status_ac91ac_idx'),
        ),
    ]
