# Generated by Django 5.0.2 on 2025-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0006_commentattachment_formatted_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='Indicates if this is a half-day attendance'),
        ),
    ]
