# Generated by Django 5.0.2 on 2025-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0006_ticketcomment_is_first_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='original_filename',
            field=models.CharField(default='placeholder.txt', max_length=255),
            preserve_default=False,
        ),
    ]
