# Generated by Django 5.0.2 on 2025-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0006_alter_shiftassignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
