# Generated by Django 5.0.2 on 2025-07-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_alter_usersession_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='idle_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
