# Generated by Django 5.0.2 on 2025-06-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_attendance_is_half_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='comment',
            field=models.ForeignKey(default=5, help_text='The comment this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trueAlign.ticketcomment'),
            preserve_default=False,
        ),
    ]
