# Generated by Django 5.0.2 on 2025-11-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_remove_attendance_regularization_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalitem',
            name='hr_comments',
            field=models.TextField(blank=True, help_text="HR's comments on this item"),
        ),
        migrations.AddField(
            model_name='appraisalitem',
            name='hr_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], help_text='HR rating', null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('hr_review', 'HR Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current appraisal status', max_length=20),
        ),
    ]
