# Generated by Django 5.1.4 on 2025-01-23 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_alter_attendance_clock_in_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'login_time'], name='trueAlign_u_user_id_81ad70_idx'),
        ),
    ]
