# Generated by Django 5.0.2 on 2025-05-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_ticketattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
