# Generated by Django 5.2.8 on 2025-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_cashbox_balance_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='nlp_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted tags, entities, and analysis data'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='normalized_description',
            field=models.TextField(blank=True, help_text='Normalized text for searching and matching'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='List of risk factors identified'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='nlp_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted tags, entities, and analysis data'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='normalized_description',
            field=models.TextField(blank=True, help_text='Normalized text for searching and matching'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='List of risk factors identified'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Risk score (0-100)'),
        ),
    ]
