# Generated by Django 5.1.4 on 2025-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_alter_presence_unique_together_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
