# Generated by Django 5.0.2 on 2025-05-05 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0007_chartofaccount_entity_transaction_dynamicparameter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('record_type', models.CharField(blank=True, max_length=50, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='trueAlign_a_user_id_18edad_idx'), models.Index(fields=['module', 'action'], name='trueAlign_a_module_bf28d0_idx'), models.Index(fields=['record_type', 'record_id'], name='trueAlign_a_record__f4b971_idx'), models.Index(fields=['created_at'], name='trueAlign_a_created_b410dd_idx')],
            },
        ),
    ]
