# Generated by Django 5.0.2 on 2025-11-13 06:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trueAlign', '0008_appraisalitem_hr_comments_appraisalitem_hr_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='assignment_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='color_code',
            field=models.CharField(default='#3B82F6', help_text='Hex color code for UI', max_length=7),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='description',
            field=models.TextField(blank=True, help_text='Shift description'),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='max_consecutive_days',
            field=models.IntegerField(default=6, help_text='Maximum consecutive working days'),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='min_rest_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.0'), help_text='Minimum rest hours before next shift', max_digits=4),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='overtime_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.0'), help_text='Hours threshold for overtime', max_digits=4),
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires approval for assignments'),
        ),
        migrations.CreateModel(
            name='ShiftConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('OVERLAP', 'Overlapping Assignments'), ('REST_VIOLATION', 'Insufficient Rest Period'), ('MAX_HOURS', 'Maximum Hours Exceeded'), ('ROLE_RESTRICTION', 'Role-Based Restriction'), ('APPROVAL_REQUIRED', 'Requires Approval')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low - Warning Only'), ('MEDIUM', 'Medium - Requires Review'), ('HIGH', 'High - Blocks Assignment'), ('CRITICAL', 'Critical - System Error')], max_length=10)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='trueAlign.shiftassignment')),
                ('conflicting_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='causing_conflicts', to='trueAlign.shiftassignment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['assignment', 'conflict_type'], name='trueAlign_s_assignm_a60a94_idx'), models.Index(fields=['severity', 'is_resolved'], name='trueAlign_s_severit_5533b4_idx'), models.Index(fields=['created_at'], name='trueAlign_s_created_4fa884_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('MIN_REST_HOURS', 'Minimum Rest Hours Between Shifts'), ('MAX_DAILY_HOURS', 'Maximum Daily Work Hours'), ('MAX_WEEKLY_HOURS', 'Maximum Weekly Work Hours'), ('ROLE_BASED_TIMING', 'Role-Based Allowed Timing'), ('SHIFT_GAP_REQUIREMENT', 'Required Gap Between Shifts'), ('OVERTIME_APPROVAL', 'Overtime Requires Approval')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'indexes': [models.Index(fields=['rule_type', 'is_active'], name='trueAlign_s_rule_ty_32cafe_idx'), models.Index(fields=['group', 'is_active'], name='trueAlign_s_group_i_7d1f1a_idx')],
                'unique_together': {('rule_type', 'group')},
            },
        ),
    ]
