# Generated by Django 5.1.4 on 2025-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0008_userdetails_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_contact_primary',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
