# Generated by Django 5.0.2 on 2025-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0008_usersession_idle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='location_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
