# Generated by Django 5.2.8 on 2025-12-02 12:22

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0008_cashtransaction_nlp_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount_allocated_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='actual_payout_bank_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='actual_payout_cash_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='cash_returned_by_employee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='formal_salary_payable_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='loan_recovery_deduction_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='shadowentry',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('USD', 'US Dollar ($)')], default='INR', editable=False, max_length=3),
        ),
    ]
