# Generated by Django 5.1.4 on 2025-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0009_alter_userdetails_emergency_contact_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contact_number_primary',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
