# Generated by Django 5.2.2 on 2025-07-16 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0009_usersession_location_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="browser",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="end_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="os",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="session_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
