# Generated by Django 5.0.2 on 2025-11-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0009_shiftassignment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmaster',
            name='shift_type',
            field=models.CharField(choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift'), ('Custom Shift', 'Custom Shift')], default='Day Shift', max_length=20),
        ),
    ]
