# Generated by Django 5.1.4 on 2025-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0009_userdetails_last_status_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('payroll', 'Payroll'), ('contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
