# Generated by Django 5.0.2 on 2025-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0002_attendance_indexes"),
        ("trueAlign", "0009_alter_cashbox_balance_currency_and_more"),
    ]

    operations = []
