# Generated by Django 5.0.2 on 2025-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0009_ticketattachment_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
