# Generated by Django 5.0.2 on 2025-05-07 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0010_alter_auditlog_user_employeesalary_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('alert_days', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='dynamicparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dynamicparameter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dynamicparameter',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='salary_structure',
        ),
        migrations.RemoveField(
            model_name='employeesalarycomponent',
            name='employee_salary',
        ),
        migrations.RemoveField(
            model_name='employeesalarycomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicetax',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salaryslipdetail',
            name='component',
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryslipdetail',
            name='salary_slip',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={},
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('party_name', models.CharField(max_length=255)),
                ('payment_reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('executed', 'Payment Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='bank_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trueAlign.bankaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_model', models.CharField(choices=[('per_order', 'Per Order'), ('per_fte', 'Per FTE'), ('hybrid', 'Hybrid')], max_length=20)),
                ('billing_cycle_start', models.DateField()),
                ('billing_cycle_end', models.DateField()),
                ('order_count', models.IntegerField(blank=True, null=True)),
                ('fte_count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent to Client'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('utility', 'Utility'), ('stationery', 'Stationery'), ('food', 'Food & Beverages'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trueAlign.department')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('journal', 'Journal')], max_length=20)),
                ('date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('party_name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Department Head Approval'), ('pending_finance', 'Pending Finance Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted to Accounts')], default='draft', max_length=25)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('department_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trueAlign.chartofaccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='trueAlign.voucher')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='CalculationRule',
        ),
        migrations.DeleteModel(
            name='DynamicParameter',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryComponent',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='InvoiceTax',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='ProductService',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SalaryComponent',
        ),
        migrations.DeleteModel(
            name='SalarySlip',
        ),
        migrations.DeleteModel(
            name='SalarySlipDetail',
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
