# Generated by Django 5.1.4 on 2025-02-23 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0010_alter_userdetails_contact_number_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_user_id_96129d_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_date_c92f26_idx',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in_time',
            new_name='clock_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out_time',
            new_name='clock_out',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='last_updated',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='notes',
            new_name='regularization_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leave_request',
        ),
        migrations.AddField(
            model_name='attendance',
            name='breaks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='leave_docs/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_retroactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Emergency'), (2, 'Medical'), (3, 'Regular')], default=3),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='suggested_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(default='Office', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Earned Leave', 'Earned Leave'), ('Loss of Pay', 'Loss of Pay'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Sabbatical', 'Sabbatical'), ('Comp Off', 'Comp Off'), ('Half Day', 'Half Day'), ('Emergency', 'Emergency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date', 'status'], name='trueAlign_a_user_id_ee39ce_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['user', 'start_date', 'status'], name='trueAlign_l_user_id_12f441_idx'),
        ),
    ]
