# Generated by Django 5.2.2 on 2025-07-18 16:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0010_usersession_browser_usersession_end_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Office location name (e.g., 'Mumbai - Bandra', 'Delhi - Gurgaon')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the location (e.g., 'MUM', 'DEL')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Additional address information",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(help_text="City name", max_length=100)),
                ("state", models.CharField(help_text="State/Province", max_length=100)),
                (
                    "postal_code",
                    models.CharField(help_text="Postal/ZIP code", max_length=20),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Office phone number", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Office email address", max_length=254
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this location active?"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Kolkata",
                        help_text="Timezone for this location",
                        max_length=50,
                    ),
                ),
                (
                    "working_hours_start",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Office working hours start time",
                    ),
                ),
                (
                    "working_hours_end",
                    models.TimeField(
                        default=datetime.time(18, 0),
                        help_text="Office working hours end time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Office Location",
                "verbose_name_plural": "Office Locations",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["office_location", "name"],
                "verbose_name": "Conference Room",
                "verbose_name_plural": "Conference Rooms",
            },
        ),
        migrations.RemoveIndex(
            model_name="userdetails",
            name="trueAlign_u_work_lo_30c0c8_idx",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="work_location",
        ),
        migrations.AlterField(
            model_name="room",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Room location/floor within the office",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(help_text="Room name", max_length=100),
        ),
        migrations.AddField(
            model_name="room",
            name="office_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Office location where this room is located",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="trueAlign.officelocation",
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="office_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Office location where the employee works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="trueAlign.officelocation",
            ),
        ),
        migrations.AddIndex(
            model_name="userdetails",
            index=models.Index(
                fields=["office_location"], name="trueAlign_u_office__bfd620_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("name", "office_location"), name="unique_room_name_per_location"
            ),
        ),
    ]
