# Generated by Django 5.0.2 on 2025-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0010_ticketattachment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
