# Generated by Django 5.0.2 on 2025-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0011_bankaccount_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyexpense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
