# Generated by Django 5.2.2 on 2025-07-18 16:17

from django.db import migrations
from datetime import time


def create_office_locations(apps, schema_editor):
    """Create default office locations and assign existing rooms to them."""
    OfficeLocation = apps.get_model('trueAlign', 'OfficeLocation')
    Room = apps.get_model('trueAlign', 'Room')
    UserDetails = apps.get_model('trueAlign', 'UserDetails')

    # Create default office locations
    office_locations = [
        {
            'name': 'Mumbai - Bandra',
            'code': 'MUM',
            'address_line1': 'Bandra Kurla Complex',
            'address_line2': 'Office Tower',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'postal_code': '400051',
            'country': 'India',
            'phone': '+91-22-12345678',
            'email': 'mumbai@company.com',
            'timezone': 'Asia/Kolkata',
            'working_hours_start': time(9, 0),
            'working_hours_end': time(18, 0),
            'is_active': True,
        },
        {
            'name': 'Delhi - Gurgaon',
            'code': 'DEL',
            'address_line1': 'Cyber City',
            'address_line2': 'DLF Phase 2',
            'city': 'Gurgaon',
            'state': 'Haryana',
            'postal_code': '122002',
            'country': 'India',
            'phone': '+91-124-12345678',
            'email': 'delhi@company.com',
            'timezone': 'Asia/Kolkata',
            'working_hours_start': time(9, 0),
            'working_hours_end': time(18, 0),
            'is_active': True,
        },
    ]

    created_offices = []
    for office_data in office_locations:
        # Check if office already exists
        try:
            office = OfficeLocation.objects.get(code=office_data['code'])
            print(f"Office location already exists: {office.name}")
        except OfficeLocation.DoesNotExist:
            office = OfficeLocation.objects.create(**office_data)
            print(f"Created office location: {office.name}")
        created_offices.append(office)

    # Get the default office location (Mumbai)
    default_office = created_offices[0]

    # Assign existing rooms to the default office location
    rooms_without_office = Room.objects.filter(office_location__isnull=True)
    for room in rooms_without_office:
        room.office_location = default_office
        room.save()
        print(f"Assigned room '{room.name}' to {default_office.name}")

    # Handle existing UserDetails - users with work_location field
    # Note: The old work_location field is being replaced with office_location
    # We can't access the old field directly in the migration, so we'll just
    # assign default office location to users without one
    users_without_office = UserDetails.objects.filter(office_location__isnull=True)
    for user_detail in users_without_office:
        user_detail.office_location = default_office
        user_detail.save()
        print(f"Assigned user '{user_detail.user.username}' to {default_office.name}")


def reverse_office_locations(apps, schema_editor):
    """Reverse the office location population."""
    OfficeLocation = apps.get_model('trueAlign', 'OfficeLocation')
    Room = apps.get_model('trueAlign', 'Room')
    UserDetails = apps.get_model('trueAlign', 'UserDetails')

    # Clear office location assignments
    Room.objects.all().update(office_location=None)
    UserDetails.objects.all().update(office_location=None)

    # Delete office locations
    OfficeLocation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0011_add_office_location"),
    ]

    operations = [
        migrations.RunPython(
            create_office_locations,
            reverse_office_locations,
        ),
    ]
