# Generated by Django 5.1.4 on 2025-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0011_remove_attendance_truealign_a_user_id_96129d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday')], default='Absent', max_length=20),
        ),
    ]
