# Generated by Django 5.1.4 on 2025-03-25 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0011_remove_leave_priority_alter_leave_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-week_start_date', '-version'], 'permissions': [('approve_timesheet', 'Can approve or reject timesheets'), ('view_team_timesheets', 'Can view timesheets for team members')]},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='adjusted_hours',
            field=models.FloatField(blank=True, help_text='Hours adjusted by manager during review', null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='original_submission_id',
            field=models.IntegerField(blank=True, help_text='ID of original submission if this is a resubmission', null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Insufficient_Detail', 'Insufficient Detail'), ('Hours_Discrepancy', 'Hours Discrepancy'), ('Wrong_Project', 'Wrong Project Allocation'), ('Incomplete_Documentation', 'Incomplete Documentation'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='task_description',
            field=models.TextField(default='', help_text='Detailed description of work performed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this timesheet entry'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Partially_Approved', 'Partially Approved'), ('Rejected', 'Rejected'), ('Clarification_Requested', 'Clarification Requested')], default='Pending', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('user', 'week_start_date', 'project', 'task_name', 'version')},
        ),
    ]
