# Generated by Django 5.1.4 on 2025-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0012_alter_timesheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
