# Generated by Django 5.0.2 on 2025-07-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0012_populate_office_locations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersession',
            table='trueAlign_usersession',
        ),
    ]
