# Generated by Django 5.0.2 on 2025-06-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0012_delete_escalationrule_and_more'),
    ]

    operations = [
    ]
