# Generated by Django 5.0.2 on 2025-05-08 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0012_alter_dailyexpense_options_alter_dailyexpense_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('text', 'Text'), ('json', 'JSON'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20)),
                ('is_global', models.BooleanField(default=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_parameters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='trueAlign_d_key_41c9a6_idx'), models.Index(fields=['entity_id', 'entity_type'], name='trueAlign_d_entity__e19b0a_idx')],
                'unique_together': {('key', 'entity_id', 'entity_type', 'valid_from')},
            },
        ),
    ]
