# Generated by Django 5.1.4 on 2025-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0013_alter_leave_approver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in',
            new_name='clock_in_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out',
            new_name='clock_out_time',
        ),
    ]
