# Generated by Django 5.0.2 on 2025-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0013_alter_usersession_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hr", "HR"),
                    ("manager", "Manager"),
                    ("team_lead", "Team Lead"),
                    ("senior_developer", "Senior Developer"),
                    ("developer", "Developer"),
                    ("junior_developer", "Junior Developer"),
                    ("intern", "Intern"),
                    ("qa_engineer", "QA Engineer"),
                    ("devops_engineer", "DevOps Engineer"),
                    ("ui_ux_designer", "UI/UX Designer"),
                    ("business_analyst", "Business Analyst"),
                    ("project_manager", "Project Manager"),
                    ("scrum_master", "Scrum Master"),
                    ("consultant", "Consultant"),
                    ("trainee", "Trainee"),
                    ("other", "Other"),
                ],
                default="developer",
                help_text="Employee role/designation in the company",
                max_length=50,
            ),
        ),
    ]
