# Generated by Django 5.0.2 on 2025-05-08 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trueAlign', '0013_dynamicparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dynamicparameter',
            name='trueAlign_d_entity__e19b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamicparameter',
            new_name='dp_key_idx',
            old_name='trueAlign_d_key_41c9a6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dynamicparameter',
            unique_together={('key', 'content_type', 'object_id', 'valid_from')},
        ),
        migrations.AddField(
            model_name='dynamicparameter',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dynamicparameter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicparameter',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicparameter',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='dynamicparameter',
            index=models.Index(fields=['content_type', 'object_id'], name='dp_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicparameter',
            index=models.Index(fields=['valid_from', 'valid_to'], name='dp_validity_idx'),
        ),
        migrations.RemoveField(
            model_name='dynamicparameter',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='dynamicparameter',
            name='entity_type',
        ),
    ]
