# Generated by Django 5.0.2 on 2025-07-23 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trueAlign", "0014_userdetails_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("scroll", "Scroll"),
                            ("keyboard", "Keyboard"),
                            ("mouse_move", "Mouse Move"),
                            ("page_view", "Page View"),
                            ("tab_visibility", "Tab Visibility"),
                            ("idle_state", "Idle State"),
                            ("heartbeat", "Heartbeat"),
                            ("location_update", "Location Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity_data", models.JSONField(blank=True, default=dict)),
                ("url", models.URLField(blank=True, max_length=2000, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("location_latitude", models.FloatField(blank=True, null=True)),
                ("location_longitude", models.FloatField(blank=True, null=True)),
                ("location_accuracy", models.FloatField(blank=True, null=True)),
                ("productivity_score", models.FloatField(blank=True, null=True)),
                ("engagement_score", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="trueAlign.usersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trueAlign_sessionactivity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "activity_type"],
                        name="session_activity_type_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_time"], name="user_activity_time_idx"
                    ),
                    models.Index(fields=["created_at"], name="activity_created_at_idx"),
                    models.Index(
                        fields=["activity_type", "activity_time"], name="type_time_idx"
                    ),
                ],
            },
        ),
    ]
