# Generated by Django 5.0.2 on 2025-05-08 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trueAlign', '0014_remove_dynamicparameter_truealign_d_entity__e19b0a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for the parameter', max_length=100)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('category', models.CharField(choices=[('tax', 'Tax'), ('fee', 'Fee'), ('rate', 'Rate'), ('threshold', 'Threshold'), ('limit', 'Limit'), ('rule', 'Rule'), ('other', 'Other')], default='other', help_text='Category for organizing parameters', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the parameter's purpose", null=True)),
                ('value', models.TextField(help_text='String representation of the parameter value')),
                ('value_type', models.CharField(choices=[('decimal', 'Decimal'), ('percentage', 'Percentage'), ('integer', 'Integer'), ('text', 'Text'), ('json', 'JSON'), ('boolean', 'Boolean'), ('date', 'Date')], help_text='Data type of the parameter', max_length=20)),
                ('is_global', models.BooleanField(default=True, help_text='If True, applies globally; if False, applies to specific entity')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the specific entity', null=True)),
                ('valid_from', models.DateField(help_text='Date from which this parameter value is valid')),
                ('valid_to', models.DateField(blank=True, help_text='Date until which this parameter value is valid (null = indefinite)', null=True)),
                ('fiscal_year', models.CharField(blank=True, help_text='Fiscal year in YYYY-YYYY format', max_length=9, null=True)),
                ('fiscal_quarter', models.CharField(blank=True, help_text='Fiscal quarter in YYYY-Q# format', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this parameter has been approved for use')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fin_parameters', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Entity type this parameter is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fin_parameters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_fin_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Parameter',
                'verbose_name_plural': 'Financial Parameters',
            },
        ),
        migrations.DeleteModel(
            name='DynamicParameter',
        ),
        migrations.AddIndex(
            model_name='financialparameter',
            index=models.Index(fields=['key'], name='fin_param_key_idx'),
        ),
        migrations.AddIndex(
            model_name='financialparameter',
            index=models.Index(fields=['category'], name='fin_param_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='financialparameter',
            index=models.Index(fields=['content_type', 'object_id'], name='fin_param_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='financialparameter',
            index=models.Index(fields=['valid_from', 'valid_to'], name='fin_param_validity_idx'),
        ),
        migrations.AddIndex(
            model_name='financialparameter',
            index=models.Index(fields=['fiscal_year'], name='fin_param_fiscal_yr_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialparameter',
            unique_together={('key', 'content_type', 'object_id', 'valid_from')},
        ),
    ]
