# Generated by Django 5.0.2 on 2025-05-09 19:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0016_leavetype_compoffrequest_leavepolicy_leaverequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'user']},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_shift_i_93e8d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_date_c92f26_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_user_id_c1b091_idx',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in_time',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out_time',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='breaks',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='expected_hours',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='regularization_status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user_session',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_departure_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_session_attendance', to='trueAlign.usersession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='idle_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_session_attendance', to='trueAlign.usersession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='left_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_location',
            field=models.CharField(default='Office', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Holiday', 'Holiday'), ('Weekend', 'Weekend'), ('Work From Home', 'Work From Home'), ('Comp Off', 'Comp Off')], default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='trueAlign_a_user_id_96129d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='trueAlign_a_date_2bbee0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_on_leave'], name='trueAlign_a_is_on_l_d4da4d_idx'),
        ),
    ]
