# Generated by Django 5.0.2 on 2025-05-09 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0017_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_user_id_ee39ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='trueAlign_a_is_on_l_d4da4d_idx',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in',
            new_name='clock_in_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out',
            new_name='clock_out_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='remarks',
            new_name='regularization_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_manual_entry',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_on_leave',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='work_location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='breaks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(choices=[('Office', 'Office'), ('Home', 'Home'), ('Remote', 'Remote'), ('Other', 'Other')], default='Office', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked')], default='Not Marked', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
