# Generated by Django 5.0.2 on 2025-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0019_attendance_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.AddField(
            model_name='attendance',
            name='requested_status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked')], help_text='Status requested by employee during regularization', max_length=20, null=True),
        ),
    ]
