# Generated by Django 5.0.2 on 2025-05-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0021_attendance_is_employee_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
