# Generated by Django 5.0.2 on 2025-05-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0022_attendance_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='remark',
            new_name='remarks',
        ),
    ]
