# Generated by Django 5.0.2 on 2025-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0025_gameicon_playerstats_tictactoegame_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='requested_status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In')], help_text='Status requested by employee during regularization', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present & Late', 'Present & Late'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Work From Home', 'Work From Home'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday'), ('Comp Off', 'Comp Off'), ('Not Marked', 'Not Marked'), ('Yet to Clock In', 'Yet to Clock In')], default='Not Marked', max_length=20),
        ),
    ]
