# Generated by Django 5.0.2 on 2025-05-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueAlign', '0027_remove_attendance_is_half_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('COMMENTED', 'Commented'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='support',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current escalation level of the ticket'),
        ),
        migrations.AddField(
            model_name='support',
            name='response_time',
            field=models.DurationField(blank=True, help_text='Time taken for first response', null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='sla_status',
            field=models.CharField(blank=True, choices=[('Within SLA', 'Within SLA'), ('Breached', 'Breached')], help_text='Status of SLA compliance', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='sla_target_date',
            field=models.DateTimeField(blank=True, help_text='Target date for SLA compliance', null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='time_to_close',
            field=models.DurationField(blank=True, help_text='Total time from creation to closure', null=True),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['resolved_at'], name='trueAlign_s_resolve_70ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['priority'], name='trueAlign_s_priorit_933347_idx'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activity', to='trueAlign.support'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
